---
# update all packages
- name: Update all packages
  ansible.builtin.apt:
    update_cache: true
    name: "*"
    state: latest
    autoclean: true
    autoremove: true
    purge: true
  when: ansible_distribution in ["Debian", "Ubuntu"]

# install extra packages
- name: Install extra
